### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by OneWebPro** [foxhound87/mobx-react-matchmedia#20]
Right now lib is creating lot of noise in if it used with [mobx-react-devtools ](https://github.com/mobxjs/mobx-react-devtools) and with many breakpoints. Good idea would be to update breakpoints using [transaction](https://mobxjs.github.io/mobx/refguide/transaction.html) probably - it will invoke one "event" change after all updates.

**Comment by foxhound87** [comment]
I added the transaction, but before releasing the new version, I should fix this:
https://github.com/mobxjs/mobx/issues/570

**Comment by OneWebPro** [comment]
Ok, thanks for info. I think it can be close then 👍 .
