### ISSUE TITLE
Can it be a single store?

### ISSUE THREAD

**Issue by Andrfas** [foxhound87/mobx-react-matchmedia#73]
So that store can be injected into any component and be used from there?

**Comment by foxhound87** [comment]
Hello @Andrfas 

the breakpoints store are intended to be read-only, they are updated only inside the React HOC, you can pass them around your app components and check each prop you define with the breakpoints. 

The react HOC will read the breakpoints strings initially, and then will transform them to observable booleans.

Hope it can help you to understand how it works. 
Please let me know if have more questions.
