### ISSUE TITLE
React PropTypes warning

### ISSUE THREAD

**Issue by simpixelated** [foxhound87/mobx-react-matchmedia#8]
Thannks for this awesome library! I was trying to look up examples of using matchMedia with mobx and found this. Works as expected, however I'm getting a couple React PropType warnings:
```sh
Warning: You are manually calling a React.PropTypes validation function for the `children` prop on `MatchMediaProvider`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

Same thing with `breakpoints` prop on `MatchMediaProvider`. I followed the example usage, so I'm not sure if it's just something on my side or not. Looking at your src, I don't see anything that would cause the warning so I'm at a loss.

**Comment by simpixelated** [comment]
I'm using older versions of React and mobx, so that could be an issue:
```sh
mobx@2.4.0
mobx-react@3.5.4
react@15.1.0
```

**Comment by simpixelated** [comment]
Looks like if I upgrade to react/react-dom @15.3.1 the warnings are gone

**Comment by foxhound87** [comment]
Hi @simpixelated 

great to hear you are enjoying this.

It's a warning I never seen, updating the libs should be the way.

But, anyway I will deepen the react docs. 

Thank you for reporting your experience and your libs version!
